# Generated by Django 5.2.13 on 2026-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='zobet/events/banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Bet (₹)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='zobet/events/teams/'),
        ),
    ]
